
export const compareUrls = [
    // row 0 spotlight
    ['/dashboard/phastr/pasc-mortality/1'],
    ['/dashboard/phastr/pasc-mortality/2'],
    ['/dashboard/phastr/pasc-mortality/3'],
    ['/dashboard/phastr/pasc-mortality/4'],
    ['/dashboard/phastr/pasc-mortality/5'],
    ['/dashboard/phastr/pasc-mortality/6'],
    ['/dashboard/phastr/pasc-mortality/7'],
    ['/dashboard/phastr/ucda/1'],
    ['/dashboard/phastr/ucda/2'],
    ['/dashboard/phastr/ucda/3'],
    ['/dashboard/phastr/ucda/4'],
    ['/dashboard/phastr/ucda/5'],
    ['/dashboard/phastr/ucda/6'],
    ['/dashboard/phastr/ucda/7'],
    ['/dashboard/phastr/ucda/8'],
    // row 1
    ['/dashboard/data-overview/demographics', 'overview-demo'],
    ['/dashboard/data-overview/multi-dimensional-summary', 'multidimensional'],
    ['/dashboard/data-overview/demographics-comorbidities', 'comorbidities'], // https://covid.clinicalcohort.org/dashboard/data-overview/feeds/demographics-comorbidities.jsp
    ['/dashboard/public-health/hss/1', 'demo-irb1'],
    ['/dashboard/public-health/hss/2', 'demo-irb2'],
    ['/dashboard/public-health/delayed-mortality/3', 'mortailty3'],
    ['/dashboard/public-health/delayed-mortality/1', 'mortality1'],
    ['/dashboard/public-health/delayed-mortality/2', 'mortality2'],
    ['/dashboard/public-health/enclave-health/3', 'enclavehealth3'],
    ['/dashboard/public-health/enclave-health/1', 'enclavehealth1'],
    ['/dashboard/public-health/enclave-health/2', 'enclavehealth2'],
    ['/dashboard/public-health/severity-region/map1', 'regional-dist'],

    // row 2
    ['/dashboard/collaborating-sites', 'row_2'],
    ['/dashboard/contributing-sites', 'row_2'],
    ['/dashboard/publications-map', 'row_2'],
    ['/dashboard/publications', 'row_2'],
    ['/dashboard/collaboration-graph', 'row_2'],
    ['/dashboard/teams', 'row_2'],
    ['/dashboard/users', 'row_2'],
    ['/dashboard/concept-sets', 'row_2'],

    // row 3
    ['/dashboard/public-health/pprl/1', 'row_3'],
    ['/dashboard/public-health/pprl/2', 'row_3'],
    ['/dashboard/public-health/pprl/3', 'row_3'],
    ['/dashboard/public-health/pprl/4', 'row_3'],
    ['/dashboard/public-health/pprl/5', 'row_3'],
    ['/dashboard/public-health/pprl/8', 'row_3'],
    ['/dashboard/public-health/pprl/9', 'row_3'],
    ['/dashboard/public-health/pprl/6', 'row_3'],
    ['/dashboard/public-health/pprl/7', 'row_3'],
    ['/dashboard/pprl', 'row_3'],
    ['/dashboard/public-health/Paxlovid/4', 'row_3'],
    ['/dashboard/public-health/Paxlovid/9', 'row_3'],
    ['/dashboard/public-health/Paxlovid/5', 'row_3'],
    ['/dashboard/public-health/Paxlovid/6', 'row_3'],
    ['/dashboard/public-health/Paxlovid/7', 'row_3'],
    ['/dashboard/public-health/Paxlovid/10', 'row_3'],
    ['/dashboard/public-health/Paxlovid/11', 'row_3'],
    ['/dashboard/public-health/Paxlovid/8', 'row_3'],
    ['/dashboard/public-health/Paxlovid/1', 'row_3'],
    ['/dashboard/public-health/Paxlovid/2', 'row_3'],
    ['/dashboard/public-health/Paxlovid/3', 'row_3'],
    ['/dashboard/public-health/timeline/1', 'row_3'],
    ['/dashboard/public-health/timeline/2', 'row_3'],
    ['/dashboard/public-health/medication-time-series/1', 'row_3'],
    ['/dashboard/public-health/medication-time-series/2', 'row_3'],

    // row 4
    ['/dashboard/public-health/reinfection/1', 'row_4'],
    ['/dashboard/public-health/reinfection/2', 'row_4'],
    ['/dashboard/public-health/reinfection/3', 'row_4'],
    ['/dashboard/public-health/reinfection-time-series/1', 'row_4'],
    ['/dashboard/public-health/reinfection-time-series/2', 'row_4'],
    ['/dashboard/public-health/timeline/1', 'row_4'],
    ['/dashboard/public-health/timeline/2', 'row_4'],

    // row5
    ['/dashboard/public-health/medications/1', 'row_5'],
    ['/dashboard/public-health/medications/2', 'row_5'],
    ['/dashboard/public-health/medications/3', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/1', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/4', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/5', 'row_5'],
    ['/dashboard/public-health/metformin/1', 'row_5'],
    ['/dashboard/public-health/metformin/5', 'row_5'],
    ['/dashboard/public-health/metformin/2', 'row_5'],
    ['/dashboard/public-health/metformin/3', 'row_5'],
    ['/dashboard/public-health/metformin/4', 'row_5'],

    // row6
    ['/dashboard/public-health/hlh/1', 'row_6'],
    ['/dashboard/public-health/hlh/2', 'row_6'],
    ['/dashboard/public-health/hlh/3', 'row_6'],
    ['/dashboard/public-health/hlh/4', 'row_6'],
    ['/dashboard/public-health/hlh/19', 'row_6'],
    ['/dashboard/public-health/hlh/20', 'row_6'],
    ['/dashboard/public-health/hlh/5', 'row_6'],
    ['/dashboard/public-health/hlh/6', 'row_6'],
    ['/dashboard/public-health/hlh/8', 'row_6'],
    ['/dashboard/public-health/hlh/9', 'row_6'],
    ['/dashboard/public-health/hlh/10', 'row_6'],
    ['/dashboard/public-health/hlh/11', 'row_6'],
    ['/dashboard/public-health/hlh/12', 'row_6'],
    ['/dashboard/public-health/hlh/13', 'row_6'],
    ['/dashboard/public-health/hlh/14', 'row_6'],
    ['/dashboard/public-health/hlh/15', 'row_6'],
    ['/dashboard/public-health/hlh/16', 'row_6'],
    ['/dashboard/public-health/hlh/17', 'row_6'],
    ['/dashboard/public-health/hlh/18', 'row_6'],
    ['/dashboard/public-health/substance-use/7', 'row_6'],
    ['/dashboard/public-health/substance-use/1', 'row_6'],
    ['/dashboard/public-health/substance-use/2', 'row_6'],
    ['/dashboard/public-health/substance-use/3', 'row_6'],
    ['/dashboard/public-health/substance-use/4', 'row_6'],
    ['/dashboard/public-health/substance-use/5', 'row_6'],
    ['/dashboard/public-health/substance-use/6', 'row_6'],
    ['/dashboard/public-health/substance-use/8', 'row_6'],
    ['/dashboard/public-health/substance-use/9', 'row_6'],
    ['/dashboard/public-health/long-covid/1', 'row_6'],
    ['/dashboard/public-health/long-covid/13', 'row_6'],
    ['/dashboard/public-health/long-covid/14', 'row_6'],
    ['/dashboard/public-health/long-covid/2', 'row_6'],
    ['/dashboard/public-health/long-covid/15', 'row_6'],
    ['/dashboard/public-health/long-covid/3', 'row_6'],
    ['/dashboard/public-health/long-covid/6', 'row_6'],
    ['/dashboard/public-health/long-covid/4', 'row_6'],
    ['/dashboard/public-health/long-covid/5', 'row_6'],
    ['/dashboard/public-health/long-covid/12', 'row_6'],
    ['/dashboard/public-health/long-covid/7', 'row_6'],
    ['/dashboard/public-health/long-covid/8', 'row_6'],
    ['/dashboard/public-health/long-covid/9', 'row_6'],
    ['/dashboard/public-health/long-covid/10', 'row_6'],
    ['/dashboard/public-health/long-covid/11', 'row_6'],
    ['/dashboard/recover/model', 'row_6'],
    ['/dashboard/recover/training', 'row_6'],
    ['/dashboard/recover/demographics', 'row_6'],
    ['/dashboard/public-health/smoking/1', 'row_6'],
    ['/dashboard/public-health/smoking/2', 'row_6'],
    ['/dashboard/public-health/environmental/6', 'row_6'],
    ['/dashboard/public-health/environmental/5', 'row_6'],
    ['/dashboard/public-health/environmental/1', 'row_6'],
    ['/dashboard/public-health/environmental/4', 'row_6'],
    ['/dashboard/public-health/environmental/2', 'row_6'],
    ['/dashboard/public-health/environmental/3', 'row_6'],
    // Add additional URL pairs here...
];