export const dashboardUrls = [


    ['https://covid.clinicalcohort.org/dashboard/', '/dashboard'],
    ['https://covid.clinicalcohort.org/dashboard/admin/institutions', '/dashboard/admin'],
    ['https://covid.clinicalcohort.org/dashboard/downloads', '/dashboard/downloads'],
    ['https://covid.cd2h.org/dashboard/collaboration-graph', '/dashboard/collaboration-graph'],
];  
  export const strapiUrls = [  
    ['https://clinicalcohort.org/', '/clinical-cohort'],
    ['https://clinicalcohort.org/forum/', '/forum'],
    ['https://clinicalcohort.org/about/news.jsp', '/press-coverage'],
    ['https://clinicalcohort.org/communications', '/communications'],
    ['https://covid.clinicalcohort.org/', '/covid'],
    ['https://covid.clinicalcohort.org/about/', '/covid/covid-about'],
    ['https://covid.clinicalcohort.org/about/misson.jsp', '/covid/mission' ],
    ['https://covid.clinicalcohort.org/contributors/', '/covid/contributor'],
    ['https://covid.clinicalcohort.org/covid-extension/', '/covid/covid-extension'],
    ['https://covid.clinicalcohort.org/enclave/', '/covid/enclave-essentials'],
    ['https://covid.clinicalcohort.org/fact-sheet/', '/covid/fact-sheet'],
    ['https://covid.clinicalcohort.org/domain-teams/', '/covid/domain-teams'],
    ['https://covid.clinicalcohort.org/projects/', '/covid/projects'],
    ['https://covid.clinicalcohort.org/tools/', '/covid/tools'],
    ['https://covid.clinicalcohort.org/external-datasets/', '/covid/external-datasets'],
    ['https://covid.clinicalcohort.org/duas/', '/covid/duas'],
    ['https://covid.clinicalcohort.org/account-instructions/', '/covid/account-creation'],
    ['https://covid.clinicalcohort.org/PPRL/', '/covid/pprl'],
    ['https://covid.clinicalcohort.org/phastr/', '/covid/phastr'],
    ['https://covid.clinicalcohort.org/for-institutions/', '/covid/institution-essentials'],
    ['https://covid.clinicalcohort.org/for-researchers/', '/covid/researcher-essentials'],
    ['https://covid.clinicalcohort.org/onboarding/', '/covid/onboarding'],
    ['https://covid.clinicalcohort.org/calendar/', '/covid/calendar'],
    ['https://covid.clinicalcohort.org/training/', '/covid/training'],
    ['https://covid.clinicalcohort.org/communications/ ', '/covid/communications'],
    ['https://covid.clinicalcohort.org/publication-review/ ', '/covid/publication-review'],
    ['https://covid.clinicalcohort.org/dur/ ', '/covid/dur'],
    ['https://covid.clinicalcohort.org/acknowledgements/ ', '/covid/acknowledgements'],
    ['https://covid.clinicalcohort.org/download/ ', '/covid/download'],
    ['https://covid.clinicalcohort.org/policy/', '/covid/policy'],
    ['https://covid.clinicalcohort.org/support/', '/covid/support'],
    ['https://covid.clinicalcohort.org/faq/ ', '/covid/faq'],
    ['https://covid.clinicalcohort.org/liaisons/ ', '/covid/liaisons'],
    ['https://covid.clinicalcohort.org/about/presentations.jsp', '/covid/presentations'],
    ['https://covid.clinicalcohort.org/forum/ ', '/covid/forum'],
    ['https://covid.clinicalcohort.org/about/news.jsp', '/covid/press-coverage'],
    ['https://education.clinicalcohort.org/', '/education'],
    ['https://education.clinicalcohort.org/duas/ ', '/covid/duas'],
    ['https://education.clinicalcohort.org/dur/ ', '/education/dur'],
    ['https://education.clinicalcohort.org/account-instructions', '/education/account-creation'],
    ['https://education.clinicalcohort.org/support/', null],
    ['https://education.clinicalcohort.org/faq/', '/covid/faq'], /// // This is for covid and education... are they the same page or does a new one need to be created
    ['https://education.clinicalcohort.org/liaisons/  ', '/covid/liaisons'], // This is for covid and education... are they the same page or does a new one need to be created///n3c/covid/liaisons
    ['https://cancer.clinicalcohort.org/', '/cancer'],
    ['https://cancer.clinicalcohort.org/participants/', '/cancer/participants'],
    ['https://renal.clinicalcohort.org/', '/renal'],
    ['https://renal.clinicalcohort.org/participants/', '/renal/participants'],

]

export const compareUrls = [
    // row 0 spotlight
    ['/dashboard/phastr/pasc-mortality/1'],
    ['/dashboard/phastr/pasc-mortality/2'],
    ['/dashboard/phastr/pasc-mortality/3'],
    ['/dashboard/phastr/pasc-mortality/4'],
    ['/dashboard/phastr/pasc-mortality/5'],
    ['/dashboard/phastr/pasc-mortality/6'],
    ['/dashboard/phastr/pasc-mortality/7'],
    ['/dashboard/phastr/ucda/1'],
    ['/dashboard/phastr/ucda/2'],
    ['/dashboard/phastr/ucda/3'],
    ['/dashboard/phastr/ucda/4'],
    ['/dashboard/phastr/ucda/5'],
    ['/dashboard/phastr/ucda/6'],
    ['/dashboard/phastr/ucda/7'],
    ['/dashboard/phastr/ucda/8'],
    // row 1
    ['/dashboard/data-overview/demographics', 'overview-demo'],
    ['/dashboard/data-overview/multi-dimensional-summary', 'multidimensional'],
    ['/dashboard/data-overview/demographics-comorbidities', 'comorbidities'], // https://covid.clinicalcohort.org/dashboard/data-overview/feeds/demographics-comorbidities.jsp
    ['/dashboard/public-health/hss/1', 'demo-irb1'],
    ['/dashboard/public-health/hss/2', 'demo-irb2'],
    ['/dashboard/public-health/delayed-mortality/3', 'mortailty3'],
    ['/dashboard/public-health/delayed-mortality/1', 'mortality1'],
    ['/dashboard/public-health/delayed-mortality/2', 'mortality2'],
    ['/dashboard/public-health/enclave-health/3', 'enclavehealth3'],
    ['/dashboard/public-health/enclave-health/1', 'enclavehealth1'],
    ['/dashboard/public-health/enclave-health/2', 'enclavehealth2'],
    ['/dashboard/public-health/severity-region/map1', 'regional-dist'],

    // row 2
    ['/dashboard/collaborating-sites', 'row_2'],
    ['/dashboard/contributing-sites', 'row_2'],
    ['/dashboard/publications-map', 'row_2'],
    ['/dashboard/publications', 'row_2'],
    ['/dashboard/collaboration-graph', 'row_2'],
    ['/dashboard/teams', 'row_2'],
    ['/dashboard/users', 'row_2'],
    ['/dashboard/concept-sets', 'row_2'],

    // row 3
    ['/dashboard/public-health/pprl/1', 'row_3'],
    ['/dashboard/public-health/pprl/2', 'row_3'],
    ['/dashboard/public-health/pprl/3', 'row_3'],
    ['/dashboard/public-health/pprl/4', 'row_3'],
    ['/dashboard/public-health/pprl/5', 'row_3'],
    ['/dashboard/public-health/pprl/8', 'row_3'],
    ['/dashboard/public-health/pprl/9', 'row_3'],
    ['/dashboard/public-health/pprl/6', 'row_3'],
    ['/dashboard/public-health/pprl/7', 'row_3'],
    ['/dashboard/pprl', 'row_3'],
    ['/dashboard/public-health/Paxlovid/4', 'row_3'],
    ['/dashboard/public-health/Paxlovid/9', 'row_3'],
    ['/dashboard/public-health/Paxlovid/5', 'row_3'],
    ['/dashboard/public-health/Paxlovid/6', 'row_3'],
    ['/dashboard/public-health/Paxlovid/7', 'row_3'],
    ['/dashboard/public-health/Paxlovid/10', 'row_3'],
    ['/dashboard/public-health/Paxlovid/11', 'row_3'],
    ['/dashboard/public-health/Paxlovid/8', 'row_3'],
    ['/dashboard/public-health/Paxlovid/1', 'row_3'],
    ['/dashboard/public-health/Paxlovid/2', 'row_3'],
    ['/dashboard/public-health/Paxlovid/3', 'row_3'],
    ['/dashboard/public-health/timeline/1', 'row_3'],
    ['/dashboard/public-health/timeline/2', 'row_3'],
    ['/dashboard/public-health/medication-time-series/1', 'row_3'],
    ['/dashboard/public-health/medication-time-series/2', 'row_3'],

    // row 4
    ['/dashboard/public-health/reinfection/1', 'row_4'],
    ['/dashboard/public-health/reinfection/2', 'row_4'],
    ['/dashboard/public-health/reinfection/3', 'row_4'],
    ['/dashboard/public-health/reinfection-time-series/1', 'row_4'],
    ['/dashboard/public-health/reinfection-time-series/2', 'row_4'],
    ['/dashboard/public-health/timeline/1', 'row_4'],
    ['/dashboard/public-health/timeline/2', 'row_4'],

    // row5
    ['/dashboard/public-health/medications/1', 'row_5'],
    ['/dashboard/public-health/medications/2', 'row_5'],
    ['/dashboard/public-health/medications/3', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/1', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/4', 'row_5'],
    ['/dashboard/public-health/MedicationsSnapshots/5', 'row_5'],
    ['/dashboard/public-health/metformin/1', 'row_5'],
    ['/dashboard/public-health/metformin/5', 'row_5'],
    ['/dashboard/public-health/metformin/2', 'row_5'],
    ['/dashboard/public-health/metformin/3', 'row_5'],
    ['/dashboard/public-health/metformin/4', 'row_5'],

    // row6
    ['/dashboard/public-health/hlh/1', 'row_6'],
    ['/dashboard/public-health/hlh/2', 'row_6'],
    ['/dashboard/public-health/hlh/3', 'row_6'],
    ['/dashboard/public-health/hlh/4', 'row_6'],
    ['/dashboard/public-health/hlh/19', 'row_6'],
    ['/dashboard/public-health/hlh/20', 'row_6'],
    ['/dashboard/public-health/hlh/5', 'row_6'],
    ['/dashboard/public-health/hlh/6', 'row_6'],
    ['/dashboard/public-health/hlh/8', 'row_6'],
    ['/dashboard/public-health/hlh/9', 'row_6'],
    ['/dashboard/public-health/hlh/10', 'row_6'],
    ['/dashboard/public-health/hlh/11', 'row_6'],
    ['/dashboard/public-health/hlh/12', 'row_6'],
    ['/dashboard/public-health/hlh/13', 'row_6'],
    ['/dashboard/public-health/hlh/14', 'row_6'],
    ['/dashboard/public-health/hlh/15', 'row_6'],
    ['/dashboard/public-health/hlh/16', 'row_6'],
    ['/dashboard/public-health/hlh/17', 'row_6'],
    ['/dashboard/public-health/hlh/18', 'row_6'],
    ['/dashboard/public-health/substance-use/7', 'row_6'],
    ['/dashboard/public-health/substance-use/1', 'row_6'],
    ['/dashboard/public-health/substance-use/2', 'row_6'],
    ['/dashboard/public-health/substance-use/3', 'row_6'],
    ['/dashboard/public-health/substance-use/4', 'row_6'],
    ['/dashboard/public-health/substance-use/5', 'row_6'],
    ['/dashboard/public-health/substance-use/6', 'row_6'],
    ['/dashboard/public-health/substance-use/8', 'row_6'],
    ['/dashboard/public-health/substance-use/9', 'row_6'],
    ['/dashboard/public-health/long-covid/1', 'row_6'],
    ['/dashboard/public-health/long-covid/13', 'row_6'],
    ['/dashboard/public-health/long-covid/14', 'row_6'],
    ['/dashboard/public-health/long-covid/2', 'row_6'],
    ['/dashboard/public-health/long-covid/15', 'row_6'],
    ['/dashboard/public-health/long-covid/3', 'row_6'],
    ['/dashboard/public-health/long-covid/6', 'row_6'],
    ['/dashboard/public-health/long-covid/4', 'row_6'],
    ['/dashboard/public-health/long-covid/5', 'row_6'],
    ['/dashboard/public-health/long-covid/12', 'row_6'],
    ['/dashboard/public-health/long-covid/7', 'row_6'],
    ['/dashboard/public-health/long-covid/8', 'row_6'],
    ['/dashboard/public-health/long-covid/9', 'row_6'],
    ['/dashboard/public-health/long-covid/10', 'row_6'],
    ['/dashboard/public-health/long-covid/11', 'row_6'],
    ['/dashboard/recover/model', 'row_6'],
    ['/dashboard/recover/training', 'row_6'],
    ['/dashboard/recover/demographics', 'row_6'],
    ['/dashboard/public-health/smoking/1', 'row_6'],
    ['/dashboard/public-health/smoking/2', 'row_6'],
    ['/dashboard/public-health/environmental/6', 'row_6'],
    ['/dashboard/public-health/environmental/5', 'row_6'],
    ['/dashboard/public-health/environmental/1', 'row_6'],
    ['/dashboard/public-health/environmental/4', 'row_6'],
    ['/dashboard/public-health/environmental/2', 'row_6'],
    ['/dashboard/public-health/environmental/3', 'row_6'],
    // Add additional URL pairs here...

    ['/'],
    ['/about'],
    ['/about/misson.jsp'],
    ['/contributors/'],
    ['/covid-extension/'],
    ['/enclave/'],
    // ['https://ncats.nih.gov/sites/default/files/OMOP_CDM_COVID.pdf'], //external!
    // ['https://zenodo.org/communities/cd2h-covid/records?q=&l=list&p=1&s=10&sort=newest'], // External!
    ['/fact-sheet/'],
    ['/domain-teams/'],
    ['/projects/'],
    ['/tools/'],
    ['/external-datasets/'],
    // ['https://ncats.nih.gov/research/research-activities/n3c/resources/data-contribution/signatories'], //External
    ['/duas/'],
    ['/account-instructions/'],
    ['/PPRL/'],
    ['/phastr/'],
    ['/for-institutions/'],
    ['/for-researchers/'],
    // ['https://national-clinical-cohort-collaborative.github.io/guide-to-n3c-v1/'], //External
    ['/onboarding/'],
    ['/calendar/'], // airtable calendar
    ['/training/'],
    // ['https://zenodo.org/communities/cd2h-covid/records?q=IRB&l=list&p=1&s=10&sort=bestmatch'], // external
    ['/communications/'],
    ['/publication-review/'],
    ['/communications/'],
    ['/dur/'],
    // ['https://ncats.nih.gov/research/research-activities/n3c/resources/data-access'], // External
    ['/acknowledgements/'],
    ['/download/'],
    ['/policy/'],
    // ['https://docs.google.com/forms/d/e/1FAIpQLSeKgUA5nmladqt16IaX1FYRNFOwRT2Nboe77qUcxOAZigQiSw/viewform'], // Google Form External
    ['/support/'],
    ['/faq/'],
    // ['https://n3c-help.atlassian.net/servicedesk/customer/portal/2'], // atlassian n3c support desk
    // [
    //     'https://teams.microsoft.com/l/meetup-join/19%3ameeting_MjAzZWZhN2UtZWFmYy00NmE5LWE0NjEtNmM3YmI1Y2VhNTU5%40thread.v2/0?context=%7b%22Tid%22%3a%2214b77578-9773-42d5-8507-251ca2dc2b06%22%2c%22Oid%22%3a%2241433e29-66a6-4bc8-baa1-f6e001a31eb1%22%7d',
    // ], // Teams External
    ['/liaisons/'],
    // ['https://docs.google.com/forms/d/e/1FAIpQLSfXhu8qReLi44kskOvPVfIjXB9qWadOYP7bKrw_H5_EHD332g/viewform'], // External Google form
    ['/about/presentations.jsp'],
    ['/forum/'],
    ['/about/news.jsp'],
    // ['https://myemail-api.cons.com/N3C-Updates.html?soid=1134197625149&aid=OvpD-Mhe3cc'], // External
];

export const domainTeamsUrls = [
    ['https://covid.cd2h.org/multiorgan', '/covid/domain-teams/domain/multiorgan'],
    ['https://covid.cd2h.org/ET-DT', '/covid/domain-teams/cross_cutting/ET-DT'],
    ['https://covid.cd2h.org/team-creation/', '/covid/domain-teams/team-creation']
];
